### ISSUE TITLE
Export QOL

### ISSUE THREAD

**Issue by GreenBlueClouds** [digits58/anitk#1]
- After processing a batch, you need to exit and reopen the program to do a new batch.

- Having an Import/export GUI similar to WebM for Bakas would be really nice.

**Comment by digits58** [comment]
Implemented in latest update, report any bugs if found to be fixed.

Current Usage
---
1. Browse for input folder
2. Browse for output folder
3. Click Analyze for anitk to check for duplicates and what the result will be
4. Click Run to proceed

![image](https://github.com/digits58/anitk/assets/115112505/0d33be4b-b2a5-438b-9892-bd47be329109)
